# See https://github.com/silverstripe/silverstripe-travis-support for setup details

language: php

sudo: false

sudo: false

php:
 - 5.5

env:
  global:
    - CORE_RELEASE=4
  matrix:
    - DB=MYSQL
    - DB=PGSQL

matrix:
  include:
    - php: 5.5
      env: DB=MYSQL BEHAT_TEST=1

before_script:
 - composer self-update || true
 - phpenv rehash
 - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
 - "if [ \"$BEHAT_TEST\" = \"\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi"
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/behat-extension; fi"
 - cd ~/builds/ss
 - php ~/travis-support/travis_setup_selenium.php --if-env BEHAT_TEST
 - php ~/travis-support/travis_setup_php54_webserver.php --if-env BEHAT_TEST

script:
 - "if [ \"$BEHAT_TEST\" = \"\" ]; then vendor/bin/phpunit subsites/tests; fi"
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then vendor/bin/behat @subsites; fi"
